name: Custom Report
description: Простой отчет
title: "[ Custom ]: -"
labels: ["bug", "triage"]
body:
  - type: textarea
    id: main-area
    attributes:
      label: "### Issue: Шаблон простого отчета."
      description: "Приведите любую информацию"
    validations:
      required: true
