name: Custom Report
description: Простой отчет
title: "[ Custom ]: -"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "### Issue: Шаблон простого отчета."

  - type: textarea
    id: main-area
    attributes:
      description: "Приведите любую информацию"
      placeholder: " "
    validations:
      required: true
