name: Feature Report
description: Добавление функционала
title: "[ Feature  ]: -"
body:
  #1
  - type: textarea
    id: short-description
    attributes:
      label: Краткое описание БП
      description: Дайте краткое описание Бизнес Процесса
      placeholder: Краткое описание назначения БП.
    validations:
      required: true
  #2
  - type: textarea
    id: participants
    attributes:
      label: Укажите участников БП
      description: Перечислите участников Бизнес процесса, связанные с этой фичей
      placeholder: |
        "Например:
          - Пользователь  
          - Администратор
          - Граф
          - Бот
          - Внешний контракт (контракт другого продукта)
          - Внешний сервис
          - др."
    validations:
      required: true
