name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add typescript
      - name: Build project
        run: yarn run build
      - name: Cache Yarn packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  test:
    name: Run tests
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Cache Yarn packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add typescript
      - name: Run tests
        run: yarn run test
      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-results
          path: ./test-results.xml
  coverage:
    name: Coverage
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: Cache Yarn packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add typescript
      - name: Run tests with coverage
        run: yarn run coverage
